[tool.poetry]
name = "agent-actions"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "n"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.26.0"
tiktoken = "^0.6.0"
flask = "^3.0.3"
flask-cors = "^4.0.1"
networkx = "^3.3"
pypdf2 = "^3.0.1"
python-docx = "^1.1.2"
pandas = "^2.2.2"
openpyxl = "^3.1.2"
beautifulsoup4 = "^4.12.3"
google-api-python-client = "^2.130.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
