"""Module for processing generated data."""
from typing import Dict, List

from agent_actions.transformers.data_transformer import DataTransformer
from agent_actions.constants import SIDE_COLLECTION_KEY
from agent_actions.processors.common.utils import transform_with_side_collection

from .interfaces import IDataProcessor


class DataProcessor(IDataProcessor):
    """Handles post-processing of generated data (Single Responsibility)."""

    def __init__(self, agent_config: Dict):
        """
        Initialize the data processor.
        
        Args:
            agent_config: Configuration for the agent
        """
        self.agent_config = agent_config

    def process_item(
        self, 
        contents: Dict, 
        generated_data: List[Dict], 
        source_guid: str,
        idx: int = 0
    ) -> List[Dict]:
        """
        Process a generated data item with transformations.
        
        Args:
            contents: Original content
            generated_data: Data generated by the agent
            source_guid: Unique identifier for the item
            idx: Index of the item
            
        Returns:
            Processed data
            
        Raises:
            ValueError: If data processing fails
        """
        try:
            return transform_with_side_collection(
                generated_data,
                contents,
                source_guid,
                self.agent_config,
                idx,
            )
        except Exception as e:
            raise ValueError(f"Failed to process item: {str(e)}")

    def separate_side_output(self, processed_items: List[Dict]) -> tuple[List[Dict], List[Dict]]:
        """
        Separate main output from side output.
        
        Args:
            processed_items: List of processed items
            
        Returns:
            Tuple of (main_output, side_output)
        """
        main_output, side_output = [], []
        
        for item in processed_items:
            content = item.get('content', {})
            if isinstance(content, dict) and content.get('side_output', False):
                side_output.append(item)
            else:
                main_output.append(item)
                
        return main_output, side_output