"""Module for processing generated data."""
from typing import Dict, Any, List

from agent_actions.transformers.data_transformer import DataTransformer

from .interfaces import IDataProcessor


class DataProcessor(IDataProcessor):
    """Handles post-processing of generated data (Single Responsibility)."""

    def __init__(self, agent_config: Dict):
        """
        Initialize the data processor.
        
        Args:
            agent_config: Configuration for the agent
        """
        self.agent_config = agent_config

    def process_item(
        self, 
        contents: Dict, 
        generated_data: List[Dict], 
        guid: str
    ) -> List[Dict]:
        """
        Process a generated data item with transformations.
        
        Args:
            contents: Original content
            generated_data: Data generated by the agent
            guid: Unique identifier for the item
            
        Returns:
            Processed data
            
        Raises:
            ValueError: If data processing fails
        """
        try:
            side_collection = self.agent_config.get('side_collection', [])
            
            if side_collection:
                # Apply side_collection transformation to each item
                updated_data = [
                    DataTransformer.update_schema_objects(contents, data, side_collection)
                    for data in generated_data
                ]
                return DataTransformer.transform_structure([{guid: updated_data}])
            else:
                # No transformation needed
                return DataTransformer.transform_structure([{guid: generated_data}])
        except Exception as e:
            raise ValueError(f"Failed to process item: {str(e)}")

    def separate_side_output(self, processed_items: List[Dict]) -> tuple[List[Dict], List[Dict]]:
        """
        Separate main output from side output.
        
        Args:
            processed_items: List of processed items
            
        Returns:
            Tuple of (main_output, side_output)
        """
        main_output, side_output = [], []
        
        for item in processed_items:
            content = item.get('content', {})
            if isinstance(content, dict) and content.get('side_output', False):
                side_output.append(item)
            else:
                main_output.append(item)
                
        return main_output, side_output