"""Static workflow analysis for compile-time type checking."""

from agent_actions.validation.static_analyzer import (
    AgentKind,
    DataFlowEdge,
    DataFlowGraph,
    DataFlowNode,
    InputRequirement,
    InputSchema,
    OutputSchema,
    ErrorSeverity,
    FieldLocation,
    StaticTypeError,
    StaticTypeIssue,
    StaticTypeWarning,
    StaticValidationResult,
    ReferenceExtractor,
    SchemaExtractor,
    StaticTypeChecker,
    WorkflowStaticAnalyzer,
    analyze_workflow,
    FieldFlowAnalyzer,
    FieldLineage,
    FieldConsumer,
    FieldReference,
    ActionFlowInfo,
    InputSchemaInfo,
    OutputFieldInfo,
    WorkflowFlow,
    ConflictDetector,
    ConflictAnalysisResult,
    Conflict,
    ConflictType,
    ConflictSeverity,
    FieldProducer,
    AffectedReference,
)

__all__ = [
    # Main entry points
    "WorkflowStaticAnalyzer",
    "analyze_workflow",
    # Graph components
    "DataFlowGraph",
    "DataFlowNode",
    "DataFlowEdge",
    "OutputSchema",
    "InputSchema",
    "InputRequirement",
    "AgentKind",
    # Extractors
    "SchemaExtractor",
    "ReferenceExtractor",
    # Type checker
    "StaticTypeChecker",
    # Field flow analyzer
    "FieldFlowAnalyzer",
    "FieldLineage",
    "FieldConsumer",
    "FieldReference",
    "ActionFlowInfo",
    "InputSchemaInfo",
    "OutputFieldInfo",
    "WorkflowFlow",
    # Errors
    "StaticValidationResult",
    "StaticTypeError",
    "StaticTypeWarning",
    "StaticTypeIssue",
    "FieldLocation",
    "ErrorSeverity",
    # Conflict detector
    "ConflictDetector",
    "ConflictAnalysisResult",
    "Conflict",
    "ConflictType",
    "ConflictSeverity",
    "FieldProducer",
    "AffectedReference",
]
