"""Centralized configuration key constants."""

MODEL_VENDOR_KEY = "model_vendor"
MODEL_NAME_KEY = "model_name"
JSON_MODE_KEY = "json_mode"
API_KEY_KEY = "api_key"
PROMPT_KEY = "prompt"
SCHEMA_NAME_KEY = "schema_name"
CHUNK_CONFIG_KEY = "chunk_config"
SIDE_COLLECTION_KEY = "side_collection"
