"""Module for processing generated data."""
from dataclasses import dataclass
from typing import Dict, List, Optional
from agent_actions.utilities.processor.processor_helpers import transform_with_passthrough
from agent_actions.utilities.processor.error_handling import ProcessorErrorHandlerMixin
from agent_actions.errors import TransformationError  # New modular pattern!
from agent_actions.configuration.interfaces import IDataProcessor, ProcessingMode
from agent_actions.orchestration.dependency_injection import registry
from agent_actions.utilities.output_splitter import split_main_and_side_outputs


@dataclass
class ProcessItemRequest:
    """Request parameters for processing a single item."""
    contents: Dict
    generated_data: List[Dict]
    source_guid: str
    idx: int = 0
    passthrough_fields: Optional[Dict] = None

@registry.register_processor('data_processor')
class DataProcessor(ProcessorErrorHandlerMixin, IDataProcessor):
    """Handles post-processing of generated data (Single Responsibility)."""

    def __init__(self, agent_config: Dict):
        """
        Initialize the data processor.

        Args:
            agent_config: Configuration for the agent
        """
        super().__init__()
        self.agent_config = agent_config

    def supports_async(self) -> bool:
        """Return True as this processor supports async operations."""
        return True

    def get_processing_mode(self) -> ProcessingMode:
        """Return AUTO processing mode to let system choose."""
        return ProcessingMode.AUTO

    def process_item(
        self,
        contents: Dict,
        generated_data: List[Dict],
        source_guid: str
    ) -> List[Dict]:
        """
        Process a generated data item with transformations.

        Args:
            contents: Original content
            generated_data: Data generated by the agent
            source_guid: Unique identifier for the item

        Returns:
            Processed data

        Raises:
            ValueError: If data processing fails
        """
        try:
            return transform_with_passthrough(
                generated_data,
                contents,
                source_guid,
                self.agent_config
            )
        except (ValueError, TypeError, KeyError) as e:
            self.handle_processing_error(
                e,
                'Processing generated data item',
                TransformationError,
                source_guid=source_guid,
                item_count=len(generated_data) if isinstance(
                    generated_data, list
                ) else 1
            )
            return None

    def separate_side_output(self, processed_items: List[Dict]) -> tuple[List[Dict], List[Dict]]:
        """
        Separate main output from side output.

        Args:
            processed_items: List of processed items

        Returns:
            Tuple of (main_output, side_output)
        """
        return split_main_and_side_outputs(processed_items)
