"""Module for processing generated data."""
import logging
from typing import Dict, List

from agent_actions.common.transformers.data_transformer import DataTransformer
from agent_actions.constants import SIDE_COLLECTION_KEY
from agent_actions.common.utils.processor_helpers import transform_with_side_collection
from agent_actions.common.utils.error_handling import ProcessorErrorHandlerMixin
from agent_actions.processors.exceptions import TransformationError

from agent_actions.common.interfaces.interfaces import IDataProcessor, ProcessingMode
from ...core.dependency_injection import registry


@registry.register_processor("data_processor")
class DataProcessor(ProcessorErrorHandlerMixin, IDataProcessor):
    """Handles post-processing of generated data (Single Responsibility)."""

    def __init__(self, agent_config: Dict):
        """
        Initialize the data processor.
        
        Args:
            agent_config: Configuration for the agent
        """
        super().__init__()
        self.agent_config = agent_config
    
    def supports_async(self) -> bool:
        """Return True as this processor supports async operations."""
        return True
    
    def get_processing_mode(self) -> ProcessingMode:
        """Return AUTO processing mode to let system choose."""
        return ProcessingMode.AUTO

    def process_item(
        self, 
        contents: Dict, 
        generated_data: List[Dict], 
        source_guid: str,
        idx: int = 0
    ) -> List[Dict]:
        """
        Process a generated data item with transformations.
        
        Args:
            contents: Original content
            generated_data: Data generated by the agent
            source_guid: Unique identifier for the item
            idx: Index of the item
            
        Returns:
            Processed data
            
        Raises:
            ValueError: If data processing fails
        """
        try:
            return transform_with_side_collection(
                generated_data,
                contents,
                source_guid,
                self.agent_config,
                idx,
            )
        except Exception as e:
            self.handle_processing_error(
                e,
                "Processing generated data item",
                TransformationError,
                source_guid=source_guid,
                item_index=idx,
                item_count=len(generated_data) if isinstance(generated_data, list) else 1
            )

    def separate_side_output(self, processed_items: List[Dict]) -> tuple[List[Dict], List[Dict]]:
        """
        Separate main output from side output.
        
        Args:
            processed_items: List of processed items
            
        Returns:
            Tuple of (main_output, side_output)
        """
        main_output, side_output = [], []
        
        for item in processed_items:
            content = item.get('content', {})
            if isinstance(content, dict) and content.get('side_output', False):
                side_output.append(item)
            else:
                main_output.append(item)
                
        return main_output, side_output